feat: add link to the github repository
voltrondata/substrait-fiddle pull request #21
Opened 2023-05-23 20:32 UTC by sanjibansg

This PR adds a link to the GitHub repository on the webpage. It will be helpful for new developers to locate the code repository for contribution.

This should resolve Issue #18

2023-05-23 20:46 UTC, sanjibansg commented on client/src/App.vue
> +                src="https://cdn.simpleicons.org/github/white"
Here, the GitHub logo hosted by [simpleicons.org](https://simpleicons.org/) is used. Will that be okay, or do we need a better option?

2023-05-23 20:46 UTC, sanjibansg commented on client/src/App.vue
> +                src="https://cdn.simpleicons.org/github/white"
They have some free-to-use icons I believe with a legal disclaimer for use, might have to check their usage, or need to give attribution. 
https://github.com/simple-icons/simple-icons

2023-05-23 20:46 UTC, sanjibansg commented on client/src/App.vue
> +                href="https://github.com/voltrondata/substrait-fiddle/"
I wanted to have something that [FastAPI](https://fastapi.tiangolo.com/) uses in their documentation webpages, and even [Substrait](https://substrait.io/). I am not very sure if they are built from scratch, or if we can use an official GitHub badge.

2023-06-07 04:16 UTC, westonpace requested changes
Can we center the link vertically so it's on the same vertical position as the "Substrait Fiddle" header?

2023-06-14 20:23 UTC, sanjibansg commented
> Can we center the link vertically so it's on the same vertical position as the "Substrait Fiddle" header?

updated this,
![Screenshot from 2023-06-15 01-53-08](https://github.com/voltrondata/substrait-fiddle/assets/40017007/2423f6e1-95bd-4797-abdc-dd75cc01f28b)

2023-06-27 04:14 UTC, westonpace approved these changes
Thanks for centering that

2023-06-27 04:14 UTC, merged